const MAX_HANDS=6,R=78,CATCH=86,SPEED=38;
const STAGES=[['heart','하트','핑크 하트 테두리'],['gem','보석','보석 상자'],['star','별','별빛 하늘'],['ribbon','리본','리본 커튼'],['crown','왕관빛','성 꼭대기 왕관'],['orb','마법구슬','오로라 배경'],['shoe','유리구두','반짝 길'],['castle','마법성','성 조명']];
const CONN=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
const $=s=>document.querySelector(s),stage=$('#stage'),welcome=$('#welcome'),target=$('#targetGem'),pointer=$('#wandPointer'),guide=$('#guide'),score=$('#score'),slots=[...document.querySelectorAll('.slot')],rewards=$('#accessoryLayer'),sparkles=$('#sparkles'),camera=$('#camera'),overlay=$('#handOverlay'),tint=$('#cameraTint'),status=$('#status'),togglePreview=$('#togglePreview'),restart=$('#restart'),start=$('#startCamera'),note=$('#parentNote'),gem=target.querySelector('.gem-heart'),label=target.querySelector('.target-label');
let count=0,mode='idle',stream=null,hands=null,raf=0,lastVideo=-1,locked=false,ready=false,busy=false,lastMove=0,activeHands=[];
const obj={x:0,y:0,vx:SPEED,vy:SPEED*.62};
const cur=()=>STAGES[Math.floor(count/3)%STAGES.length],prog=()=>count%3,done=()=>Math.floor(count/3);
function statusText(t){status.textContent=t;status.classList.toggle('hidden',!t)}
function showCam(on){camera.classList.toggle('hidden',!on);overlay.classList.toggle('hidden',!on);tint.classList.toggle('hidden',!on);stage.classList.toggle('camera-mode',on)}
function size(){overlay.width=stage.clientWidth;overlay.height=stage.clientHeight}
function reset(){count=0;locked=false;lastMove=0;activeHands=[];score.textContent='0';rewards.innerHTML='';renderRewards();setItem();updateSlots();target.classList.remove('hidden','collecting','caught');place(true);guide.textContent=`${cur()[1]}빛을 3개 모아요`}
function begin(){mode='camera';welcome.classList.add('hidden');restart.classList.remove('hidden');pointer.classList.remove('hidden');reset();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function draw(list){const c=overlay.getContext('2d');size();c.clearRect(0,0,overlay.width,overlay.height);list.forEach((lm,i)=>{const hue=i%2?'150,116,255':'255,112,178';c.lineCap='round';c.lineJoin='round';c.strokeStyle=`rgba(${hue},.78)`;c.lineWidth=5;CONN.forEach(([a,b])=>{if(!lm[a]||!lm[b])return;c.beginPath();c.moveTo(lm[a].x*overlay.width,lm[a].y*overlay.height);c.lineTo(lm[b].x*overlay.width,lm[b].y*overlay.height);c.stroke()});c.fillStyle=`rgba(${hue},.96)`;c.strokeStyle='rgba(255,255,255,.9)';c.lineWidth=2.5;lm.forEach(p=>{c.beginPath();c.arc(p.x*overlay.width,p.y*overlay.height,5.5,0,Math.PI*2);c.fill();c.stroke()})})}
function place(resetV=false){const b=stage.getBoundingClientRect(),m=Math.min(R,b.width*.18),w=Math.max(1,b.width-m*2),h=Math.max(1,b.height-m*2);obj.x=m+w*(.22+Math.random()*.56);obj.y=m+h*(.2+Math.random()*.48);if(resetV){obj.vx=(Math.random()>.5?1:-1)*SPEED*(.72+Math.random()*.35);obj.vy=(Math.random()>.5?1:-1)*SPEED*(.5+Math.random()*.28)}renderTarget()}
function renderTarget(){target.style.left=obj.x+'px';target.style.top=obj.y+'px'}
function setItem(){const s=cur();target.dataset.kind=s[0];gem.innerHTML=itemSvg(s[0]);label.textContent=s[1]}
function defs(){return '<defs><linearGradient id="silver" x1="20" y1="8" x2="100" y2="112"><stop stop-color="#fff"/><stop offset=".35" stop-color="#f4f7ff"/><stop offset=".68" stop-color="#ffc4e3"/><stop offset="1" stop-color="#bd7cff"/></linearGradient><radialGradient id="pink" cx=".34" cy=".25" r=".72"><stop stop-color="#fff"/><stop offset=".3" stop-color="#ffd9ee"/><stop offset=".74" stop-color="#ff68ad"/><stop offset="1" stop-color="#9a2a72"/></radialGradient></defs>'}
function itemSvg(t){const d=defs();if(t==='heart')return `<svg viewBox="0 0 120 110">${d}<path class="item-main" d="M60 101C24 75 8 56 10 34c2-17 16-27 32-22 8 2 14 8 18 16 4-8 10-14 18-16 16-5 30 5 32 22 2 22-14 41-50 67Z" fill="url(#pink)"/><path class="item-shine" d="M31 30c8-10 20-10 28 1" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".72"/></svg>`;if(t==='gem')return `<svg viewBox="0 0 120 110">${d}<path class="item-main" d="M28 12h64l20 31-52 58L8 43 28 12Z" fill="url(#silver)"/><path d="M28 12 44 43 60 12 76 43 92 12M8 43h104M44 43l16 58 16-58" fill="none" stroke="#fff" stroke-width="4" opacity=".56"/></svg>`;if(t==='star')return `<svg viewBox="0 0 120 120">${d}<path class="item-main" d="M60 6 74 42l39 3-30 25 9 39-32-21-32 21 9-39L7 45l39-3L60 6Z" fill="url(#silver)"/><path class="item-shine" d="M43 39 55 27" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".8"/></svg>`;if(t==='ribbon')return `<svg viewBox="0 0 120 120">${d}<path class="item-main" d="M58 43C36 24 19 22 9 38c-8 13 1 31 24 36l25-22Zm4 0c22-19 39-21 49-5 8 13-1 31-24 36L62 52Z" fill="url(#pink)"/><circle cx="60" cy="54" r="16" fill="url(#silver)" stroke="#fff" stroke-width="4"/></svg>`;if(t==='crown')return `<svg viewBox="0 0 130 110">${d}<path class="item-main" d="M14 80 22 32l27 28 16-42 17 42 29-28 7 48c-30 13-75 13-104 0Z" fill="url(#silver)"/><circle cx="65" cy="58" r="12" fill="url(#pink)" stroke="#fff" stroke-width="4"/></svg>`;if(t==='orb')return `<svg viewBox="0 0 120 120">${d}<circle class="item-main" cx="60" cy="60" r="44" fill="url(#silver)"/><path d="M32 48c10-19 32-29 53-18" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".72"/></svg>`;if(t==='shoe')return `<svg viewBox="0 0 130 110">${d}<path class="item-main" d="M20 75c27-1 51-9 71-35 7 7 17 16 27 20-7 19-29 28-62 28H25c-8 0-12-11-5-13Z" fill="url(#silver)"/><path d="M78 43c8 12 20 18 35 18M36 76c22-1 42-8 58-23" fill="none" stroke="#fff" stroke-width="6" stroke-linecap="round" opacity=".7"/></svg>`;return `<svg viewBox="0 0 130 120">${d}<path class="item-main" d="M19 102V56h18V35l18-17 18 17v21h18V41l18-17 18 17v61Z" fill="url(#silver)"/><path d="M45 102V73c0-11 8-19 18-19s18 8 18 19v29" fill="url(#pink)" stroke="#fff" stroke-width="4"/></svg>`}
function move(t){if(locked||target.classList.contains('hidden')){lastMove=t;return}if(!lastMove){lastMove=t;return}const b=stage.getBoundingClientRect(),dt=Math.min((t-lastMove)/1e3,.05),m=Math.min(R,b.width*.18);lastMove=t;obj.x+=obj.vx*dt;obj.y+=obj.vy*dt;if(obj.x<m||obj.x>b.width-m){obj.vx*=-1;obj.x=Math.max(m,Math.min(b.width-m,obj.x))}if(obj.y<m||obj.y>b.height-m){obj.vy*=-1;obj.y=Math.max(m,Math.min(b.height-m,obj.y))}renderTarget()}
function point(x,y){pointer.style.left=x+'px';pointer.style.top=y+'px';if(locked||target.classList.contains('hidden'))return;const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),cx=tr.left-sr.left+tr.width/2,cy=tr.top-sr.top+tr.height/2,dist=Math.hypot(cx-x,cy-y),pull=CATCH*2.6;if(dist<pull){const p=Math.max(0,1-dist/pull)*.08;obj.x+=(x-cx)*p;obj.y+=(y-cy)*p;renderTarget()}if(dist<CATCH)collect();else guide.textContent=dist<pull?'조금만 더 가까이!':`${cur()[1]}빛을 3개 모아요`}
function collect(){if(locked)return;locked=true;target.classList.add('caught');burst();count++;score.textContent=String(count);updateSlots();renderRewards();target.classList.add('hidden');guide.textContent=rewardText();setTimeout(()=>{locked=false;setItem();place(true);target.classList.remove('hidden','caught')},560)}
function updateSlots(){const f=prog()===0&&count>0?3:prog();slots.forEach((s,i)=>s.classList.toggle('filled',i<f))}
function rewardText(){if(prog()!==0)return `${cur()[1]} ${prog()}/3`;const c=STAGES[(done()-1+STAGES.length)%STAGES.length];if(done()>0&&done()%STAGES.length===0)return '마법 왕국 한 바퀴 완성! 더 반짝여요';return `${c[2]} 켜졌어요`}
function renderRewards(){const n=Math.min(STAGES.length,done()),cycle=Math.floor(done()/STAGES.length);stage.dataset.current=cur()[0];stage.dataset.cycle=String(cycle);const r=[];if(n>=1)r.push(`<div class="reward-hearts">${marks('♥',18)}</div>`);if(n>=2)r.push('<div class="reward-chest"><span></span><i></i><b></b></div>');if(n>=3)r.push(`<div class="reward-stars">${marks('✦',15)}</div>`);if(n>=4)r.push('<div class="reward-ribbons"><span></span><span></span></div>');if(n>=5)r.push(`<div class="reward-castle-crown">${smallCrown()}</div>`);if(n>=6)r.push('<div class="reward-aurora"></div>');if(n>=7)r.push(`<div class="reward-shoe-path">${marks('✧',12)}</div>`);if(n>=8)r.push('<div class="reward-castle-light"></div>');rewards.innerHTML=r.join('')}
function marks(mark,n){return Array.from({length:n},(_,i)=>{const side=i%4,o=8+(i*23)%82,st=side===0?`left:${o}%;top:5%`:side===1?`right:5%;top:${o}%`:side===2?`left:${o}%;bottom:6%`:`left:5%;top:${o}%`;return `<i style="${st};--d:${i*80}ms">${mark}</i>`}).join('')}
function smallCrown(){return '<svg viewBox="0 0 130 100"><path d="M10 76 18 28l28 28 18-40 19 40 30-28 7 48c-31 13-79 13-110 0Z" fill="#eef3ff" stroke="#fff" stroke-width="5"/><circle cx="65" cy="58" r="11" fill="#ff74b8" stroke="#fff" stroke-width="4"/><path d="M28 74c23 8 69 8 92 0" stroke="#fff" stroke-width="7" stroke-linecap="round"/></svg>'}
function burst(){const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),x=tr.left-sr.left+tr.width/2,y=tr.top-sr.top+tr.height/2;for(let i=0;i<12;i++){const sp=document.createElement('span');sp.className='spark';sp.textContent=i%3?'✦':'♥';sp.style.left=x+(Math.random()-.5)*110+'px';sp.style.top=y+(Math.random()-.5)*82+'px';sp.style.animationDelay=i*28+'ms';sparkles.append(sp);setTimeout(()=>sp.remove(),1e3)}}
function load(src,global){return new Promise((res,rej)=>{if(window[global])return res();const old=document.querySelector(`script[src="${src}"]`);if(old){old.addEventListener('load',res,{once:true});old.addEventListener('error',rej,{once:true});return}const sc=document.createElement('script');sc.src=src;sc.crossOrigin='anonymous';sc.onload=res;sc.onerror=()=>rej(new Error('손 인식 프로그램을 불러오지 못했습니다.'));document.head.append(sc)})}
function onHands(r){const list=(r.multiHandLandmarks||[]).slice(0,MAX_HANDS);draw(list);activeHands=[];const b=stage.getBoundingClientRect();list.forEach(lm=>{const p=lm[9];if(p)activeHands.push({x:(1-p.x)*b.width,y:p.y*b.height})});if(!activeHands.length)return;const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),tx=tr.left-sr.left+tr.width/2,ty=tr.top-sr.top+tr.height/2;let best=activeHands[0],bd=Infinity;activeHands.forEach(h=>{const d=Math.hypot(h.x-tx,h.y-ty);if(d<bd){bd=d;best=h}});point(best.x,best.y)}
async function init(){start.disabled=true;start.textContent='카메라를 준비하고 있어요...';note.textContent='카메라 사용 허용 창이 나오면 허용을 눌러 주세요.';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});camera.srcObject=stream;showCam(true);togglePreview.classList.remove('hidden');togglePreview.textContent='내 모습 숨기기';begin();guide.textContent='내 모습이 보여요! 손 인식을 준비해요...';statusText('손 인식 준비 중...');await camera.play();await load('https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js','Hands');hands=new window.Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:MAX_HANDS,modelComplexity:0,minDetectionConfidence:.45,minTrackingConfidence:.45});hands.onResults(onHands);if(hands.initialize)await hands.initialize();ready=true;statusText('');guide.textContent=`${cur()[1]}빛을 3개 모아요`}catch(e){console.error(e);ready=false;guide.textContent='손 인식에 문제가 있어요. 카메라와 조명을 확인해 주세요.';statusText('확인용 오류: '+(e?.message||'손 인식 준비 실패'));start.disabled=false;start.textContent='다시 시작하기'}}
async function loop(){if(mode==='idle')return;move(performance.now());if(ready&&camera.readyState>=2&&camera.currentTime!==lastVideo&&!busy){lastVideo=camera.currentTime;busy=true;try{await hands.send({image:camera})}catch(e){statusText('확인용 오류: '+(e?.message||'손 인식 실행 실패'))}finally{busy=false}}raf=requestAnimationFrame(loop)}
start.addEventListener('click',init);restart.addEventListener('click',reset);togglePreview.addEventListener('click',()=>{const on=camera.classList.contains('hidden');showCam(on);togglePreview.textContent=on?'내 모습 숨기기':'내 모습 보기'});window.addEventListener('resize',size);window.addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop())});