const MAX_HANDS=6,MAX_FACES=3,STAR_RADIUS=78,CATCH_RADIUS=86,STAR_SPEED=38;
const SEQ=['heart','heart','heart','gem','gem','gem','star','star','star','gem','heart','star'];
const TYPES=['star','heart','gem'],COLORS=['#ff5fa8','#a66bff','#5ea8ff','#5ee6ff'];
const CONN=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
const $=s=>document.querySelector(s);
const stage=$('#stage'),welcome=$('#welcome'),target=$('#targetGem'),guide=$('#guide'),score=$('#score'),slots=[...document.querySelectorAll('.slot')],accessory=$('#accessoryLayer'),sparkles=$('#sparkles'),camera=$('#camera'),overlay=$('#handOverlay'),tint=$('#cameraTint'),status=$('#status'),togglePreview=$('#togglePreview'),restart=$('#restart'),start=$('#startCamera'),note=$('#parentNote'),gem=target.querySelector('.gem-heart'),label=target.querySelector('.target-label'),pointer=$('#wandPointer');
let stream,hands,face,mode='idle',ready=false,handBusy=false,faceBusy=false,lastVideo=-1,lastFace=0,lastSeen=0,faces=[],palms=[],count=0,locked=false,lastMove=0,item='heart',enhance=0,raf=0;
const star={x:0,y:0,vx:STAR_SPEED,vy:STAR_SPEED*.62};
function load(src,global){return new Promise((res,rej)=>{if(window[global])return res();const old=document.querySelector(`script[src="${src}"]`);if(old){old.addEventListener('load',res,{once:true});old.addEventListener('error',rej,{once:true});return}const sc=document.createElement('script');sc.src=src;sc.crossOrigin='anonymous';sc.onload=res;sc.onerror=()=>rej(new Error('손 인식 프로그램을 불러오지 못했습니다.'));document.head.append(sc)})}
function showCam(on){camera.classList.toggle('hidden',!on);overlay.classList.toggle('hidden',!on);tint.classList.toggle('hidden',!on);stage.classList.toggle('camera-mode',on)}
function msg(t){status.textContent=t;status.classList.toggle('hidden',!t)}
function size(){overlay.width=stage.clientWidth;overlay.height=stage.clientHeight}
function nextItem(){item=count<SEQ.length?SEQ[count]:TYPES[(count-SEQ.length)%TYPES.length];target.dataset.kind=item;gem.innerHTML=itemSvg(item);label.textContent=item==='heart'?'하트빛':item==='gem'?'보석빛':'별빛'}
function itemSvg(t){if(t==='heart')return `<svg viewBox="0 0 120 110" aria-hidden="true"><defs><linearGradient id="h" x1="22" y1="10" x2="96" y2="100"><stop stop-color="#fff"/><stop offset=".25" stop-color="#ffd6eb"/><stop offset=".68" stop-color="#ff67ad"/><stop offset="1" stop-color="#b82275"/></linearGradient></defs><path class="item-main" d="M60 101C24 75 8 56 10 34c2-17 16-27 32-22 8 2 14 8 18 16 4-8 10-14 18-16 16-5 30 5 32 22 2 22-14 41-50 67Z" fill="url(#h)" stroke="#fff" stroke-width="3"/><path class="item-shine" d="M31 30c8-10 20-10 28 1" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".72"/></svg>`;if(t==='gem')return `<svg viewBox="0 0 120 110" aria-hidden="true"><defs><linearGradient id="g" x1="20" y1="8" x2="98" y2="105"><stop stop-color="#fff"/><stop offset=".28" stop-color="#ffd8ef"/><stop offset=".62" stop-color="#ff70b4"/><stop offset="1" stop-color="#8a42f5"/></linearGradient></defs><path class="item-main" d="M28 12h64l20 31-52 58L8 43 28 12Z" fill="url(#g)" stroke="#fff" stroke-width="3"/><path d="M28 12 44 43 60 12 76 43 92 12M8 43h104M44 43l16 58 16-58" fill="none" stroke="#fff" stroke-width="4" opacity=".56"/><path class="item-shine" d="M33 27h18" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".82"/></svg>`;return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="s" x1="18" y1="9" x2="100" y2="110"><stop stop-color="#fff"/><stop offset=".3" stop-color="#f7f8ff"/><stop offset=".62" stop-color="#f7b3d4"/><stop offset="1" stop-color="#cfd6e7"/></linearGradient></defs><path class="item-main" d="M60 6 74 42l39 3-30 25 9 39-32-21-32 21 9-39L7 45l39-3L60 6Z" fill="url(#s)" stroke="#fff" stroke-width="3"/><path class="item-shine" d="M43 39 55 27" stroke="#fff" stroke-width="8" stroke-linecap="round" opacity=".8"/></svg>`}
function place(reset=false){const b=stage.getBoundingClientRect(),m=Math.min(STAR_RADIUS,b.width*.18),w=Math.max(1,b.width-m*2),h=Math.max(1,b.height-m*2);star.x=m+w*(.25+Math.random()*.5);star.y=m+h*(.22+Math.random()*.42);if(reset){star.vx=(Math.random()>.5?1:-1)*STAR_SPEED*(.72+Math.random()*.35);star.vy=(Math.random()>.5?1:-1)*STAR_SPEED*(.5+Math.random()*.28)}renderTarget()}
function renderTarget(){target.style.left=star.x+'px';target.style.top=star.y+'px'}
function reset(){count=0;locked=false;lastMove=0;faces=[];palms=[];enhance=0;score.textContent='0';slots.forEach(s=>s.classList.remove('filled'));accessory.innerHTML='';accessory.style.setProperty('--gem-color',COLORS[0]);target.classList.remove('hidden','collecting','caught');nextItem();place(true);guide.textContent='손을 반짝이 가까이 가져가요'}
function begin(){mode='camera';welcome.classList.add('hidden');restart.classList.remove('hidden');pointer.classList.remove('hidden');reset();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function move(t){if(locked||target.classList.contains('hidden')){lastMove=t;return}if(!lastMove){lastMove=t;return}const b=stage.getBoundingClientRect(),dt=Math.min((t-lastMove)/1e3,.05),m=Math.min(STAR_RADIUS,b.width*.18);lastMove=t;star.x+=star.vx*dt;star.y+=star.vy*dt;if(star.x<m||star.x>b.width-m){star.vx*=-1;star.x=Math.max(m,Math.min(b.width-m,star.x))}if(star.y<m||star.y>b.height-m){star.vy*=-1;star.y=Math.max(m,Math.min(b.height-m,star.y))}renderTarget()}
function updatePointer(x,y){pointer.style.left=x+'px';pointer.style.top=y+'px';if(locked||target.classList.contains('hidden'))return;const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),cx=tr.left-sr.left+tr.width/2,cy=tr.top-sr.top+tr.height/2,d=Math.hypot(cx-x,cy-y),pull=CATCH_RADIUS*2.6;if(d<pull){const p=Math.max(0,1-d/pull)*.08;star.x+=(x-cx)*p;star.y+=(y-cy)*p;renderTarget()}if(d<CATCH_RADIUS){guide.textContent='잡았다!';collect()}else guide.textContent=d<pull?'조금만 더 가까이!':'손을 반짝이 가까이 가져가요'}
function collect(){if(locked)return;locked=true;target.classList.add('caught');burst();count++;score.textContent=String(count);progress();target.classList.add('hidden');guide.textContent=reward();setTimeout(()=>{locked=false;nextItem();place(true);target.classList.remove('hidden','caught')},520)}
function progress(){const inStep=count%3,filled=count>0&&inStep===0?3:inStep;slots.forEach((s,i)=>s.classList.toggle('filled',i<filled||count>=12));enhance=Math.max(0,count-12);accessory.style.setProperty('--gem-color',COLORS[Math.floor(enhance/2)%COLORS.length]);accessory.style.setProperty('--sparkle-power',String(Math.min(1.8,1+enhance*.08)));renderAccessories()}
function reward(){if(count===3)return'하트 귀걸이가 반짝!';if(count===6)return'보석 목걸이도 생겼어요';if(count===9)return'별빛 드레스가 켜졌어요';if(count===12)return'실버 왕관까지 완성!';if(count>12)return'보석빛이 더 강해져요';return'좋아요, 계속 모아봐요'}
function burst(){const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),x=tr.left-sr.left+tr.width/2,y=tr.top-sr.top+tr.height/2;for(let i=0;i<9;i++){const sp=document.createElement('span');sp.className='spark';sp.textContent=i%2?'♥':'✦';sp.style.left=x+(Math.random()-.5)*100+'px';sp.style.top=y+(Math.random()-.5)*75+'px';sp.style.animationDelay=i*32+'ms';sparkles.append(sp);setTimeout(()=>sp.remove(),1000)}}
function draw(list){const c=overlay.getContext('2d');size();c.clearRect(0,0,overlay.width,overlay.height);list.forEach((lm,hi)=>{const hue=hi%2?'150,116,255':'255,112,178';c.lineCap='round';c.lineJoin='round';c.strokeStyle=`rgba(${hue},.78)`;c.lineWidth=5;CONN.forEach(([a,b])=>{if(!lm[a]||!lm[b])return;c.beginPath();c.moveTo(lm[a].x*overlay.width,lm[a].y*overlay.height);c.lineTo(lm[b].x*overlay.width,lm[b].y*overlay.height);c.stroke()});c.fillStyle=`rgba(${hue},.96)`;c.strokeStyle='rgba(255,255,255,.9)';c.lineWidth=2.5;lm.forEach(p=>{c.beginPath();c.arc(p.x*overlay.width,p.y*overlay.height,5.5,0,Math.PI*2);c.fill();c.stroke()})})}
function onHands(r){const list=(r.multiHandLandmarks||[]).slice(0,MAX_HANDS);draw(list);palms=[];const b=stage.getBoundingClientRect();list.forEach(lm=>{const p=lm[9];if(p)palms.push({x:(1-p.x)*b.width,y:p.y*b.height})});if(palms.length){const tr=target.getBoundingClientRect(),sr=stage.getBoundingClientRect(),tx=tr.left-sr.left+tr.width/2,ty=tr.top-sr.top+tr.height/2;let best=palms[0],bd=Infinity;palms.forEach(p=>{const d=Math.hypot(p.x-tx,p.y-ty);if(d<bd){bd=d;best=p}});updatePointer(best.x,best.y)}}
function box(d){const r=d?.locationData?.relativeBoundingBox,b=d?.boundingBox;if(r)return{xMin:r.xMin,yMin:r.yMin,width:r.width,height:r.height};if(b?.xCenter!==undefined)return{xMin:b.xCenter-b.width/2,yMin:b.yCenter-b.height/2,width:b.width,height:b.height};return null}
function onFace(r){const got=(r.detections||[]).map(box).filter(Boolean).sort((a,b)=>a.xMin-b.xMin).slice(0,MAX_FACES);if(got.length){lastSeen=performance.now();faces=got.map((f,i)=>smooth(f,faces[i]))}else if(performance.now()-lastSeen>1200)faces=[];renderAccessories()}
function smooth(n,p){if(!p)return n;const a=.34;return{xMin:p.xMin+(n.xMin-p.xMin)*a,yMin:p.yMin+(n.yMin-p.yMin)*a,width:p.width+(n.width-p.width)*a,height:p.height+(n.height-p.height)*a}}
function facePos(b){const st=stage.getBoundingClientRect(),cx=b.xMin+b.width/2,cy=b.yMin+b.height/2;return{x:(1-cx)*st.width,y:cy*st.height,width:b.width*st.width,height:b.height*st.height,scale:Math.min(1.24,Math.max(.62,b.width*4.1))}}
function renderAccessories(){const level=Math.min(4,Math.floor(count/3));accessory.innerHTML=faces.map((f,i)=>setSvg(facePos(f),level,i)).join('')}
function setSvg(p,l,i){const dots=Array.from({length:Math.min(10,3+enhance)},(_,k)=>{const a=k/Math.min(10,3+enhance)*Math.PI*2,r=62+k%3*14;return `<i class="magic-dot" style="--x:${Math.cos(a)*r}px;--y:${Math.sin(a)*r*.65}px;--d:${k*80}ms"></i>`}).join('');return `<div class="princess-set princess-${i}" style="left:${p.x}px;top:${p.y}px;--face-w:${p.width}px;--face-h:${p.height}px;--scale:${p.scale}">${l>=3?'<div class="dress-glow"></div>':''}${l>=4?crown():''}${l>=1?ear():''}${l>=2?neck():''}${l>=4?dots:''}</div>`}
function crown(){return `<svg class="accessory crown-filter" viewBox="0 0 260 150" aria-hidden="true"><defs><linearGradient id="silverCrown" x1="32" y1="8" x2="226" y2="136"><stop stop-color="#fff"/><stop offset=".34" stop-color="#c9d2e5"/><stop offset=".55" stop-color="#fff"/><stop offset="1" stop-color="#eef3ff"/></linearGradient><radialGradient id="pinkGem" cx=".35" cy=".25" r=".76"><stop stop-color="#fff"/><stop offset=".22" stop-color="#ffdff3"/><stop offset=".62" stop-color="var(--gem-color)"/><stop offset="1" stop-color="#8d2166"/></radialGradient></defs><path class="silver-piece" d="M19 113 33 44l47 40 50-70 50 70 49-40 12 69c-55 26-166 26-222 0Z" fill="url(#silverCrown)" stroke="#fff" stroke-width="5"/><path d="M33 103c55 18 139 18 194 0l-6 28c-52 18-127 18-180 0Z" fill="#dfe6f5" stroke="#fff" stroke-width="4"/><ellipse class="jewel main-jewel" cx="130" cy="78" rx="22" ry="25" fill="url(#pinkGem)" stroke="#fff" stroke-width="4"/><circle class="jewel" cx="76" cy="88" r="14" fill="url(#pinkGem)" stroke="#fff" stroke-width="3"/><circle class="jewel" cx="184" cy="88" r="14" fill="url(#pinkGem)" stroke="#fff" stroke-width="3"/><path d="M53 101c44 12 112 13 154 0M121 67c6-8 14-8 20 0" fill="none" stroke="#fff" stroke-width="7" stroke-linecap="round" opacity=".72"/></svg>`}
function ear(){return `<svg class="accessory earrings-filter" viewBox="0 0 240 112" aria-hidden="true"><defs><radialGradient id="earGem" cx=".35" cy=".25" r=".7"><stop stop-color="#fff"/><stop offset=".3" stop-color="#ffd7ef"/><stop offset="1" stop-color="var(--gem-color)"/></radialGradient></defs><g><circle cx="52" cy="28" r="12" fill="#eef3ff" stroke="#fff" stroke-width="3"/><path d="M52 39c-11 17-18 31-18 42 0 12 8 20 18 20s18-8 18-20c0-11-7-25-18-42Z" fill="url(#earGem)" stroke="#fff" stroke-width="4"/></g><g><circle cx="188" cy="28" r="12" fill="#eef3ff" stroke="#fff" stroke-width="3"/><path d="M188 39c-11 17-18 31-18 42 0 12 8 20 18 20s18-8 18-20c0-11-7-25-18-42Z" fill="url(#earGem)" stroke="#fff" stroke-width="4"/></g></svg>`}
function neck(){return `<svg class="accessory necklace-filter" viewBox="0 0 240 112" aria-hidden="true"><defs><radialGradient id="neckGem" cx=".35" cy=".24" r=".72"><stop stop-color="#fff"/><stop offset=".34" stop-color="#ffd7ef"/><stop offset="1" stop-color="var(--gem-color)"/></radialGradient></defs><path d="M45 18c33 63 117 63 150 0" fill="none" stroke="#eef3ff" stroke-width="11" stroke-linecap="round"/><path d="M64 31c30 38 82 38 112 0" fill="none" stroke="#bfc8dc" stroke-width="4"/><path d="M120 76 99 42h42Z" fill="url(#neckGem)" stroke="#fff" stroke-width="4"/></svg>`}
async function init(){start.disabled=true;start.textContent='카메라를 준비하고 있어요...';note.textContent='카메라 사용 허용 창이 나오면 허용을 눌러 주세요.';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});camera.srcObject=stream;showCam(true);togglePreview.classList.remove('hidden');togglePreview.textContent='내 모습 숨기기';begin();guide.textContent='내 모습이 보여요! 마법을 준비하고 있어요...';msg('손 인식 준비 중...');await camera.play();await load('https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js','Hands');hands=new window.Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:MAX_HANDS,modelComplexity:0,minDetectionConfidence:.45,minTrackingConfidence:.45});hands.onResults(onHands);if(hands.initialize)await hands.initialize();try{await load('https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js','FaceDetection');face=new window.FaceDetection({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/${f}`});face.setOptions({model:'full',minDetectionConfidence:.45});face.onResults(onFace);if(face.initialize)await face.initialize()}catch(e){face=null}ready=true;msg('');guide.textContent='움직이는 빛을 손으로 잡아주세요'}catch(e){console.error(e);ready=false;guide.textContent='손 인식에 문제가 있어요. 카메라와 조명을 확인해 주세요.';msg('확인용 오류: '+(e?.message||'손 인식 준비 실패'));start.disabled=false;start.textContent='다시 시작하기'}}
async function loop(){if(mode==='idle')return;move(performance.now());if(ready&&camera.readyState>=2&&camera.currentTime!==lastVideo){lastVideo=camera.currentTime;if(hands&&!handBusy){handBusy=true;hands.send({image:camera}).catch(e=>msg('확인용 오류: '+(e?.message||'손 인식 실행 실패'))).finally(()=>handBusy=false)}const now=performance.now();if(face&&!faceBusy&&now-lastFace>90){lastFace=now;faceBusy=true;face.send({image:camera}).catch(()=>face=null).finally(()=>faceBusy=false)}}raf=requestAnimationFrame(loop)}
start.addEventListener('click',init);restart.addEventListener('click',reset);togglePreview.addEventListener('click',()=>{const on=camera.classList.contains('hidden');showCam(on);togglePreview.textContent=on?'내 모습 숨기기':'내 모습 보기'});window.addEventListener('resize',size);window.addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop())});